env:
  matrix:
    - WITH_CMAKE=true VTK60=true PREBUILD_ITKVTK=true

language: cpp

addons:
  apt:
    packages:
    - cmake
    - tcl8.5
    - tk8.5
    - tcl8.5-dev
    - tk8.5-dev
    - tcllib
    - gfortran
    sources:
    - kubuntu-backports

compiler: gcc

git:
  submodules: false

before_install:
  - export NUM_THREADS=2
  - export cwd=$(pwd)
  - export SCRIPTS=$cwd/travis
  - export EXTERNALS_DIR=$cwd/external/
  - export VTK_SOURCE_DIR=$EXTERNALS_DIR/vtk-6.0
  - export VTK_DIR=$EXTERNALS_DIR/vtk-6.0-build
  - export ITK_SOURCE_DIR=$EXTERNALS_DIR/itk-4.5
  - export ITK_DIR=$EXTERNALS_DIR/itk-4.5-build
  - export BUILD_DIR=$cwd/build
  - sudo apt-get install -qq mpich2 tklib

cache:
  apt: true
  directories:
  - $EXTERNALS_DIR

before_script:
  - $SCRIPTS/travis_build_vtk.sh
  - $SCRIPTS/travis_build_itk.sh
  #- if ! $WITH_CMAKE; then $ fi

script: $SCRIPTS/travis_build_and_test.sh

